#!/usr/bin/env bun
import { chmodSync, cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const out = join(root, ".release", "npm")
const tmp = join(root, ".release", "tmp-build")

const bins = ["cheapcode", "cheapcode-accounts", "cheapcode-account-status", "cheapcode-accounts-mcp"] as const

function run(cmd: string[], cwd = root) {
  const proc = Bun.spawnSync(cmd, { cwd, stdout: "inherit", stderr: "inherit" })
  if (!proc.success) process.exit(proc.exitCode || 1)
}

function writeExecutable(path: string, content: string) {
  writeFileSync(path, content)
  chmodSync(path, 0o755)
}

rmSync(out, { recursive: true, force: true })
rmSync(tmp, { recursive: true, force: true })
mkdirSync(join(out, "dist", "bin"), { recursive: true })
mkdirSync(join(tmp, "bin"), { recursive: true })

cpSync(join(root, "src"), join(tmp, "src"), { recursive: true })
for (const bin of bins) {
  cpSync(join(root, "bin", bin), join(tmp, "bin", `${bin}.ts`))
  run([
    "bun",
    "build",
    join(tmp, "bin", `${bin}.ts`),
    "--target=node",
    "--outdir",
    join(out, "dist", "bin"),
    "--entry-naming",
    `${bin}.js`,
  ])
  chmodSync(join(out, "dist", "bin", `${bin}.js`), 0o755)
}

run([
  "bun",
  "build",
  join(root, "src", "cheapcode-tiers.ts"),
  "--target=node",
  "--outdir",
  join(out, "dist"),
  "--entry-naming",
  "cheapcode-tiers.js",
])

const sourcePkg = await Bun.file(join(root, "package.json")).json()
const pkg = {
  name: "cheapcode-ai",
  version: sourcePkg.version,
  description: sourcePkg.description,
  type: "module",
  license: sourcePkg.license,
  homepage: "https://github.com/MahmoodKhalil57/cheapcode",
  repository: {
    type: "git",
    url: "git+https://github.com/MahmoodKhalil57/cheapcode.git",
  },
  main: "./dist/cheapcode-tiers.js",
  exports: {
    ".": {
      import: "./dist/cheapcode-tiers.js",
    },
  },
  bin: Object.fromEntries(bins.map((bin) => [bin, `./dist/bin/${bin}.js`])),
  files: ["dist", "README.md", "LICENSE"],
  engines: {
    node: ">=22",
  },
  keywords: sourcePkg.keywords,
}

writeFileSync(join(out, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`)
for (const file of ["README.md", "LICENSE"]) {
  if (existsSync(join(root, file))) cpSync(join(root, file), join(out, file))
}

writeExecutable(
  join(out, "README-packaging.txt"),
  "This directory is generated by `bun script/build-npm-package.ts`. Run `npm pack .` here to produce the vanilla-Homebrew-style tarball.\n",
)

rmSync(tmp, { recursive: true, force: true })
console.log(`built npm package at ${out}`)
